# ─────────────────────────────────────────────────────────────────────────
#  Mavi Ton Terminal Teması
# ─────────────────────────────────────────────────────────────────────────

# ── Cursor & Selection Colours ───────────────────────────────────────────
[colors.cursor]
cursor = "#528bff"
text   = "#9cdef2"

[colors.selection]
text       = "#9cdef2"
background = "#3e4451"

# ── Primary Colours ───────────────────────────────────────────────────────
[colors.primary]
background = "#282c34"
foreground = "#9cdef2"

# ── Normal Palette (Tüm mavi tonlar) ─────────────────────────────────────
[colors.normal]
black   = "#2e3440"
red     = "#61afef"     # Mavi
green   = "#9cdef2"     # Açık mavi
yellow  = "#88c0d0"     # Cyan mavi
blue    = "#528bff"     # Parlak mavi
magenta = "#7ba3d6"     # Açık mavi
cyan    = "#9cdef2"     # Açık mavi
white   = "#afc9e0"     # Çok açık mavi

# ── Bright Colors (Parlak mavi tonlar) ──────────────────────────────────
[colors.bright]
black   = "#4c566a"     # Koyu gri-mavi
red     = "#81aff5"     # Parlak mavi
green   = "#b3e5f7"     # Çok açık mavi
yellow  = "#a8d0e0"     # Pastel mavi
blue    = "#6eb5ff"     # Çok parlak mavi
magenta = "#9bb8e0"     # Soft mavi
cyan    = "#b3e5f7"     # Çok açık mavi
white   = "#d0e5f0"     # Beyazımsı mavi

# ── Font Settings ────────────────────────────────────────────────────────
[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style  = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style  = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style  = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Regular"

# ── Mouse & Environment ───────────────────────────────────────────────────
[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
